### ISSUE TITLE
Confirmation sign up email

### ISSUE THREAD

**Issue by PlutoniumF** [drawpile/website#13]
So the issue is that the sign up confirmation email wont go through. I tried to send it a couple of times but it doesnt show up anywhere. plase help

**Comment by Bluestrings-Drawpile** [comment]
This is often times because of being directed to the spam e-mail. Have you checked there?

**If I don't get a response within 7 days, I'll close out your issue.**

_**As a side note**_, if you do have Discord, you can get help faster there potentially by joining it. The invite link is found on Drawpile.net in the bottom left, or you can use this one ( https://discord.gg/M3yyMpC ). I'm a moderator there and I go by Bluestrings. If you do join and get the problem solved there, please make note of it on GitHub here so the issue can be closed. If not, no worries, I can help you here.
