### ISSUE TITLE
Crop - Preview selection in Web Gallery.

### ISSUE THREAD

**Issue by erik90mx** [drawpile/website#15]
Hi,

I recently was exploring my user account in Drawpile.net, to imagine more ways to merge the experience between Drawpile and its web page.

In my personal opinion, the Gallery is one of the strongest points to use and know Drawpile, because every draw a person did, can be stored and shared in this place.

I was exploring my own gallery (sadly I just have 1 picture in it), and remember why I didn't used a lot, like my main option to store my drawings:
https://drawpile.net/gallery/user/2857/?tab=drawings

This is what I see when I first come in:
![image](https://user-images.githubusercontent.com/3485891/55376973-332c9000-54d0-11e9-82a5-d0942823423f.png)

If I do a mouse over at what seems like an empty spot, the problem shows up:
![image](https://user-images.githubusercontent.com/3485891/55377003-5c4d2080-54d0-11e9-88a6-9a42799b3795.png)

This is the actual image:
![image](https://user-images.githubusercontent.com/3485891/55377048-7a1a8580-54d0-11e9-9537-21fa16fe786d.png)

The problem for me, was that I can't select what part of the image I want to use to apear as a preview / thumbnail of the image, because it is picked automatically.

Why is this important?
- A lot of artist like the details, and be able to know with anticipation "how it will see in the gallery" make them very happy.
- You can end with apparently empty spots like mine in the gallery.
- It can attract to more users, to share their content in the Web (for me it was the main issue, why I didn't continue sharing)

Regards

**Comment by callaa** [comment]
Yes, a thumbnail crop feature would be useful.

But I think the gallery section needs a redesign overall, anyway, to make it more useful.

**Comment by Bluestrings-Drawpile** [comment]
https://drawpile.net/news/cleanup-2019/

> The Gallery section is going away. New submissions are disabled and the entire section will be deleted sometime in the future. In its place, a new Community (name pending) section will be added. The community page will be a place to list your own communities, the server(s) it uses, community specific terms of service, moderator contacts, etc.

I'm closing this issue since it's no longer relevant. If you have concerns, please feel free to join the Drawpile Discord listed below and read the #Community text channel for a discussion as to why these changes are happening.

_**As a side note**_, if you do have Discord, you can post suggestions there by joining it and even discussing the viability of such suggestions. The invite link is found on Drawpile.net in the bottom left, or you can use this one ( https://discord.gg/M3yyMpC ). I'm a moderator there and I go by Bluestrings. If you do join, reference this suggestion and start a conversation!
