### ISSUE TITLE
File Type Save Options?

### ISSUE THREAD

**Issue by LupinWulf** [drawpile/website#2]
So Drawpile is a fantastic tool to be able to co-op on drawing projects and one of the absolute best ones out there I have found. It's fantastically user-friendly, has a wonderful selection of features to allow fantastic variation in both art style and detailing, and runs wonderfully smoothly in the user interface. Unfortunately, one of the biggest and sadly one of the hardest problems I've found with it is the file type support or lack thereof. As an art program that allows you to create and edit images with layering support, it's rather a crying shame that the only file type it can both save in and upload is .ora files. That one fact makes trying to move any picture you may have created with someone else into a different art program nearly impossible without a secondary middle program to change the file type, if most people can even find that. I do really and truly love and appreciate this program, but I really do wish it added just a bit more support there. Even just adding a simplified version of a .psd would be incredibly welcome, since even most non-photoshop art programs still have support to both save and load files of that type. This is only a suggestion, and sadly I know so little about exactly how filetype saving works, so a request like that might be a lot more difficult then I think it is, but all the same. I'm sure I'm not the only one who would so greatly appreciate such a feature.

Thank you for your consideration of this though and even more for making a program like this possible in the first place. I hope to hear back from you soon. 

-LupinWulf

**Comment by callaa** [comment]
Hi, and thank you for interest! This feature has been requested before and is on the TODO list (Issue 260.) The photoshop file format is very complex and I haven't yet found a good library for reading/writing it, which is why I haven't implemented this feature yet. However, Krita does have PSD import/export and I think I should be able to adapt their code.

I think I'll try implementing this in the 2.1 branch, which I'll start working on soon.

I'm closing this issue now since it's a duplicate and because it's related to the application itself rather than the website. (This is the website's repository. The application has a [separate issue tracker](https://github.com/drawpile/Drawpile/issues))
