### ISSUE TITLE
Ability to bypass bans by deleting registered account and creating a new one

### ISSUE THREAD

**Issue by iwannadiehard** [drawpile/website#29]
The title says it all. If you got banned from session, delete your account and create it again (even with the same name) you can get into session again.
What weird is if you keep the same name and you got locked/muted and banned, the mute and lock will stick to your name, but ban won't.

**Comment by iwannadiehard** [comment]
Ok, locked and muted stick only visually

**Comment by askmeaboutlo0m** [comment]
(I've taken over development on Drawpile, so I'm going through these tickets and organizing them.)

Yeah, the website shouldn't allow you to keep deleting and recreating accounts. Moving it there.

**Comment by askmeaboutlo0m** [comment]
Session bans have been improved in the 2.2 server to try a bit harder to recognize if someone is the same person, so if the server is up to date, recreating an account won't be enough anymore to get back into a session that banned you. The website also now doesn't delete accounts instantly, it instead puts the account into a "pending deletion" state for 30 days and only actually deletes it after that time is up, so that avenue is patched up too.

Thanks for reporting it!
