### ISSUE TITLE
Error message: Group Membership needed

### ISSUE THREAD

**Issue by rhwong** [drawpile/website#33]
I am trying to use this project to build an independent ex-auth server.
After everything is completed, I create communities on the website, just like in drawpile.net.
When I do not set *User Group* in the dp-srv, the client connects normally and the moderator has permission. Everything seems normal.
But when I set the *User Group* to *Community Sulg* in the dp-srv, the client cannot connect.
![image](https://github.com/drawpile/website/assets/58497504/912e4d3e-02a9-4d71-9bfe-cf480ad34480)
Error message: Group Membership needed.
Am I missing some necessary actions? T T

**Comment by askmeaboutlo0m** [comment]
Most likely you need to switch the ext-auth `GROUP_IMPL` in your local_settings.py to actually use the communities, rather than the default one:

```python
DRAWPILE_EXT_AUTH = {
    'PRIVATE_KEY': ...,
    'PUBLIC_KEY': ...,
    'GROUP_IMPL': 'communities.extauth.community_membership_extauth',
}
```

If you set up everything else correctly, that should end up working. There may be other reasons it falls through to not considering the user a member of the group, the relevant code is here: <https://github.com/drawpile/website/blob/master/communities/extauth.py>

Does that solve it?

**Comment by rhwong** [comment]
Thank you!!! Let me give it a try.

**Comment by rhwong** [comment]
It's working properly now. Thankssss!!! ^^

**Comment by askmeaboutlo0m** [comment]
Cool! Happy it's resolved.
