### ISSUE TITLE
cant log in despite correct information?

### ISSUE THREAD

**Issue by Gingercupcake** [drawpile/website#7]
hey!! so im trying to make an account on the drawpile website, and i figured that i just mustve forgotten my password or smth so i reset it-- and despite knowing i very much put in the correct password i was still told that i was putting in incorrect information. 

i dont recall ever changing my username, unless i was wrong about how putting in a different nickname doesnt change your account name. in which case, i'd have no idea what my current username would be due to the fact that i used to use a different one everytime i went into certain public boards.

**Comment by callaa** [comment]
Your main nickname is the one you use to log in to drawpile.net website with. Send me an email and I'll check your account.

**Comment by Gingercupcake** [comment]
hello!! thank you for the quick response-- the username i started with was
pinktiger, which is what ive been trying to log in with but it says it isnt
correct for some reason

**Comment by callaa** [comment]
The username does exist, but the first letter is capitalized. Try logging in as "Pinktiger". (There's no reason for the check to be case sensitive; I should fix that.)

I also changed the password reset email template so that the username is now included. If you forget your username, you can now recover it using the password reset feature.

**Comment by Gingercupcake** [comment]
logging in with the first letter capitalized worked!! thank you so much for
your help, the update to the reset email will be a definite help in the
future too!
